on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          tag_prefix: "v"

  build-and-push-image:
    needs: release-on-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - id: rel
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: jpillsbu
          repo: nft-site
          excludes: prerelease, draft

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          repository: ${{ github.repository }}
          tags: latest, ${{ steps.rel.outputs.release }}
