on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Tag & Release
        id: release_step
        uses: rymndhng/release-on-push-action@0.27.0
        with:
          bump_version_scheme: patch
          tag_prefix: "v"
          use_github_release_notes: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Container
        run: |
          docker build -t "$REGISTRY"/"$IMAGE_NAME":latest \
            -t "$REGISTRY"/"$IMAGE_NAME":${{ steps.release_step.outputs.tag_name }} .
          docker push -a "$REGISTRY"/"$IMAGE_NAME"
